export enum path {
  HOME = '/home',
  LOGIN = '/login',
  REGISTRATION = '/registration',
  FORGOT = '/forgot',
  RESERVATION = '/reservation',
  CLIENT = '/client',
  LOG = '/log',
  // ROOM = '/room',
  ADMIN = '/admin',
  USER = '/user',
  CHECKOUT = '/checkout',
  // SETTINGS = '/settings',
  SETTINGS_ROOM = '/settings/room',
  SETTINGS_SERVICES = '/settings/services',
  SETTINGS_ROOMVIEW = '/settings/roomview',
  SETTINGS_ROOMTYPE = '/settings/roomtype',
  SETTINGS_ROOMSTATUS = '/settings/roomstatus',
  SETTINGS_ROOMBED = '/settings/bed',
  SETTINGS_RESERVATIONSTATUS = '/settings/reservationstatus',
  SETTINGS_SERVICESTATUS = '/settings/servicestatus',
  SETTINGS_HOTEL = '/settings/hotel',
  SETTINGS_USERS = '/settings/users',
}